### ISSUE TITLE
Makes gulp run slower instead of faster

### ISSUE THREAD

**Issue by agrublev** [bingnz/gulp-less-changed#6] opened 2017-12-22 08:20 UTC
Here is my setup:

1 stylesheet called "stylesheet.less" which contains about 30 @import statements including random items.

If I try to watch the files separately and build them one by one and concat they can't compile because they depend on another 3-5 stylesheets. 

So i thought this module would look at stylesheet.less and only compile imports that have changed. Unfortunately when I try to do just that it makes compiling stylesheet.less 4-5s. When i just remove the lessChanged it goes down to 2-3s.

**Comment by bingnz** [comment] 2017-12-31 11:35
Hi,

Does it make compilation slower just the first time you compile, or every time?
You'll get benefit from this plugin in a couple of different situations. 1) if you have multiple top-level files instead of just one - for example, if you compile different style sheets for different parts of your site and you only work on one part at a time, or 2) if your gulp process is complicated and does other things beyond compiling css - so for example you don't wait for the css to compile if you've only been changing Javascript.
I think the problem is that with this particular file structure, if you change any of your files you'll have to recompile everything: so you'll be paying for the initial time to inspect whether there have been any changes, and then the time to compile everything. What I'd expect to see is that if nothing has changed it'd be very quick, but if you change anything at all it'd be slow. What I'd suggest is to see if you can break down this file with lots of imports into a few smaller files. If you can't (maybe you have an SPA for example), then you might not get any benefit from using this plugin.

**Comment by bingnz** [comment] 2018-01-18 14:19
Hi @agrublev, do you have any follow up on this? If not I will close the issue in a few days (you can always create another one if you have more information).
Thanks,
David

**Closed** 2018-02-03 11:51 UTC
